DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
baseurl = "https://OpenBagTwo.github.io"
metaDataFormat = "yaml"
theme = "blist"
title = "OpenBagTwo's Project Hub"

[build]
writeStats = true

[languages]

[languages.en]
contentDir = "content/en"  # English
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "About"
url = "page/about"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 2

[[languages.en.menu.main]]
name = "Tags"
url = "tags"
weight = 3

[languages.en.params]
introPhoto = "/openbagtwo_profile_pic.png"
introSubtitle = "And this is the stuff I do for fun"
introTitle = "I'm  Gili \"OpenBagTwo\" Barlev"
logo = "/sync_city.png"

# syntax highlight settings
[markup]

[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true

[markup.highlight]
style = "dracula"

[[menu.main]]
name = "About"
url = "/page/about"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
# Color for the intro details and social links block, not applicable for dark mode
# Supported values: Any color from TailwindCSS default colors
# Reference: https://tailwindcss.com/docs/customizing-colors
ascentColor = "bg-blue-100"
# Custom copyright - optional
copyright = "Copyright © 2023 - Gili \"OpenBagTwo\" Barlev · All rights reserved"
# Enable the darkmode toggle in header
darkModeToggle = true
# Enable search in header
enableSearch = true
# The page bundle that is shown on the front page
frontBundle = "blog"
# Used to hide the post metadata such as posted date, reading time and word count
# Can be used at site level or page level
hideMeta = false
# To hide "Other languages" option if the post is available in multiple languages
# Can be used at site level or page level
hideOtherLanguages = false
# Hides the thumbnail in post view
# Thumbnails in home and blog pages will still be shown
# This setting can also be in page's markdown file
hidePageThumbnail = false
# Option to customize the search parameters of a page
# Below are the supported options; Note that including entire content
# may slowdown the loading of search results
# Title of page is included by default
searchKeys = [
  "tags",
  "date",
  "categories",
  "summary",
  "content",
  "link",
  "author"
]
# Add support for Table of contents
# Can be added to a page level also in markdown frontmatter
toc = true

# Comments system
[params.comments]
category = ""
categoryid = ""
emitmetadata = ""
inputposition = ""
mapping = ""
reactionsenabled = ""
# Options for giscus, exclude hyphens
repo = ""
repoid = ""
strict = ""
# Supports disqus, giscus and utterances
# Check hugo docs for setting up disqus
system = "giscus"
theme = ""

[params.homepage.social]
description = "Where else you can find me"
# Global params common for both languages
title = "Social Media"

[[params.homepage.social.icons]]
url = "https://github.com/OpenBagTwo"
website = "github"

[[params.homepage.social.icons]]
url = "https://modrinth.com/user/OpenBagTwo"
website = "modrinth"

[[params.homepage.social.icons]]
url = "https://www.linkedin.com/in/gsbarlev/"
website = "linkedin"

[[params.homepage.social.icons]]
url = "https://reddit.com/u/OpenBagTwo"
website = "reddit"
